### ISSUE TITLE
"zfs" command seg faults during cli_root setup tests

### ISSUE THREAD

**Issue by mattmacy** [zfsonfreebsd/ZoF#16]
```
#0  strcmp () at /usr/home/mmacy/devel/freebsd/lib/libc/amd64/string/strcmp.S:60
#1  0x00000008008cfa9a in qsort (a=0x800bbf000, n=<optimized out>, es=8, cmp=0x8002e0020 <zprop_compare>) at /usr/home/mmacy/devel/freebsd/lib/libc/stdlib/qsort.c:128
#2  0x00000008002dffae in zprop_iter_common (func=0x20d7c0 <get_usage+16>, cb=<optimized out>, show_all=B_FALSE, ordered=<optimized out>, type=(ZFS_TYPE_FILESYSTEM | ZFS_TYPE_SNAPSHOT | ZFS_TYPE_VOLUME))
    at ../../module/zcommon/zprop_common.c:212
#3  0x000000000020d441 in usage (requested=B_FALSE) at zfs_main.c:506
#4  0x000000000020fdd9 in zfs_do_set (argc=<optimized out>, argv=<optimized out>) at zfs_main.c:3799
#5  0x000000000020d165 in main (argc=12255264, argv=0x21b148) at zfs_main.c:8005
```

**Comment by mattmacy** [comment]
fixed
